//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public int Phone { get; set; }
        public string OrdynatorName { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
