//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicinesOrder
    {
        public MedicinesOrder()
        {
            this.MedicineOrderDetails = new HashSet<MedicineOrderDetail>();
        }
    
        public int MedicinesOrderID { get; set; }
        public int PharmacistID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double Price { get; set; }
        public string RealizationFlag { get; set; }
        public Nullable<System.DateTime> RealizationDate { get; set; }
    
        public virtual ICollection<MedicineOrderDetail> MedicineOrderDetails { get; set; }
        public virtual Pharmacist Pharmacist { get; set; }
    }
}
