//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.PackageofMedicines = new HashSet<PackageofMedicine>();
            this.MedicineOrderDetails = new HashSet<MedicineOrderDetail>();
        }
    
        public int MedicineID { get; set; }
        public string TradeName { get; set; }
        public string ActiveSubstance { get; set; }
        public int Dose_mg_ { get; set; }
        public int QuantityPerUnit { get; set; }
        public Nullable<double> UnitPrice_EUR_ { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int UnitsInStock { get; set; }
        public Nullable<int> RequiredQuantity { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PackageofMedicine> PackageofMedicines { get; set; }
        public virtual ICollection<MedicineOrderDetail> MedicineOrderDetails { get; set; }
    }
}
