//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineOrderDetail
    {
        public int MedicineOrderDetailsID { get; set; }
        public int MedicinesOrderID { get; set; }
        public int MedicineID { get; set; }
        public int Amount { get; set; }
        public int Price { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual MedicinesOrder MedicinesOrder { get; set; }
    }
}
