//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersView
    {
        public string DepartmentName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Order_status { get; set; }
        public Nullable<System.DateTime> RealizationDate { get; set; }
        public string PharmacistLastName { get; set; }
    }
}
