//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.PackageToOrders = new HashSet<PackageToOrder>();
        }
    
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public int MedicineID { get; set; }
        public int Amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<PackageToOrder> PackageToOrders { get; set; }
    }
}
