//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageofMedicine
    {
        public PackageofMedicine()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.PackageToOrders = new HashSet<PackageToOrder>();
        }
    
        public int SerialNumber { get; set; }
        public int MedicineID { get; set; }
        public System.DateTime TermofValidity { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<PackageToOrder> PackageToOrders { get; set; }
    }
}
