//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageToOrder
    {
        public int PackageToOrderID { get; set; }
        public int OrderDetailID { get; set; }
        public Nullable<int> SerialNumber { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual PackageofMedicine PackageofMedicine { get; set; }
    }
}
