//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacist
    {
        public Pharmacist()
        {
            this.Orders = new HashSet<Order>();
            this.NewMedicineOrders = new HashSet<NewMedicineOrder>();
        }
    
        public int PharmacistID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<NewMedicineOrder> NewMedicineOrders { get; set; }
    }
}
